services:

  backend:
    build: ./backend
    container_name: ejecutor_backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    container_name: ejecutor_frontend
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - backend
    restart: always
